ADC_BASSES
    BANKSEL ADPCH
    MOVLW b'00000000'
    MOVWF ADPCH,1
    BANKSEL ANSELA
    BSF ANSELA,0
    BSF ADCON0,ADGO 
    labelB
    BTFSC ADCON0,ADGO 
    GOTO labelB 
    BANKSEL ADRESH 
    MOVF ADRESH,W 
    MOVWF RESULTHIGH ;changer RESULTHI en RESULTBHI, RESULTMBHI etc...
    BANKSEL ADRESL 
    MOVF ADRESL,W 
    MOVWF RESULTLOW ;pareil
    RETURN 1
 
ADC_MEDIUM_BAS
    BANKSEL ADPCH
    MOVLW b'00000001'
    MOVWF ADPCH,1
    BANKSEL ANSELA 
    BSF ANSELA,1
    BSF ADCON0,ADGO 
    labelMB
    BTFSC ADCON0,ADGO 
    GOTO labelMB 
    BANKSEL ADRESH 
    MOVF ADRESH,W 
    MOVWF RESULTHIGH ;changer RESULTHI en RESULTBHI, RESULTMBHI etc...
    BANKSEL ADRESL 
    MOVF ADRESL,W 
    MOVWF RESULTLOW ;pareil
    RETURN 1

 
ADC_MEDIUM_HAUT
    BANKSEL ADPCH
    MOVLW b'00000010'
    MOVWF ADPCH,1
    BANKSEL ANSELA 
    BSF ANSELA,2 
    BSF ADCON0,ADGO 
    labelMH
    BTFSC ADCON0,ADGO 
    GOTO labelMH 
    BANKSEL ADRESH 
    MOVF ADRESH,W 
    MOVWF RESULTHIGH ;changer RESULTHI en RESULTBHI, RESULTMBHI etc...
    BANKSEL ADRESL 
    MOVF ADRESL,W 
    MOVWF RESULTLOW ;pareil
    RETURN 1
 
ADC_AIGUS
    BANKSEL ADPCH
    MOVLW b'00000011'
    MOVWF ADPCH,1
    BANKSEL ANSELA
    BSF ANSELA,3
    BSF ADCON0,ADGO 
    labelA
    BTFSC ADCON0,ADGO 
    GOTO labelA 
    BANKSEL ADRESH 
    MOVF ADRESH,W 
    MOVWF RESULTHIGH ;changer RESULTHI en RESULTBHI, RESULTMBHI etc...
    BANKSEL ADRESL 
    MOVF ADRESL,W 
    MOVWF RESULTLOW ;pareil
    RETURN 1
 
 
GETSIGNALS
    CLRF RESULTHIGH
    CLRF RESULTLOW
    CALL ADC_BASSES
    ;CALL FROM1024TO8
    MOVWF puissanceB

    CLRF RESULTHIGH
    CLRF RESULTLOW
    CALL ADC_MEDIUM_BAS
    ;CALL FROM1024TO8
    MOVWF puissanceMB

    CLRF RESULTHIGH
    CLRF RESULTLOW
    CALL ADC_MEDIUM_HAUT
    ;CALL FROM1024TO8
    MOVWF puissanceMH

    CLRF RESULTHIGH
    CLRF RESULTLOW
    CALL ADC_AIGUS
    ;CALL FROM1024TO8
    MOVWF puissanceA

    ;passe a l affichage
    ;CALL BASSES
    ;CALL MEDIUM_BAS
    ;CALL MEDIUM_HAUT
    ;CALL AIGUS
    ;CALL LED_END
    RETURN 1
 
 
 
;*******************************************************************************
; MAIN PROGRAM
;*******************************************************************************

MAIN_PROG CODE                      ; let linker place main program

STARTPRGM

    ; TODO Step #5 - Insert Your Program Here

    BANKSEL ADCON0 
    MOVLW b'10000100'
    MOVWF ADCON0,1 
    BANKSEL ADCON1 
    MOVLW b'00000000' 
    MOVWF ADCON1,1
    BANKSEL ADCLK
    MOVLW b'00111111'
    MOVWF ADCLK,1
    BANKSEL ADCON2
    MOVLW b'00000000'
    MOVWF ADCON2,1
    BANKSEL ADACQ
    CLRF ADACQ,1
    BANKSEL ADPRE
    CLRF ADPRE,1
    BANKSEL ADREF
    MOVLW b'00010011'
    MOVWF ADREF,1
    BANKSEL FVRCON
    MOVLW b'11000010'
    MOVWF FVRCON,1

   MOVLW b'00000000'
   MOVWF OSCCON1


   
   
   
   MOVLW b'11001111'
   MOVWF TRISB

   MOVLW b'11111111'
   MOVWF TRISA

   clignote
      CALL GETSIGNALS

   GOTO clignote
   END
   